### ISSUE TITLE
Error en esp_get_prov_siane(): undefined columns selected

### ISSUE THREAD

**Issue by catbru** [rOpenSpain/mapSpain#115]
**Descripción**
Hola, estoy experimentando un error al ejecutar la función esp_get_prov_siane() del paquete mapSpain. Al intentar obtener los datos de províncias obtengo este error:

```
Error in `[.data.frame`(x, i, j, drop = drop): undefined columns selected
Backtrace:
  9. └─mapSpain::esp_get_prov_siane()
 10.   ├─data_sf[, namesend]
 11.   └─sf:::`[.sf`(data_sf, , namesend)
 12.     ├─x[i, j, drop = drop]
 13.     └─base::`[.data.frame`(x, i, j, drop = drop)
```

Ejecuto la función mapSpain::esp_get_prov_siane() en consola.
La función falla con el error indicado arriba.

**Entorno de desarrollo**

Versión del paquete mapSpain: 0.9.2
Versión de R: 4.4.2
Sistema operativo: Ubuntu 24.04

Aparece el error en los tests del repo: https://github.com/rOpenSpain/mapSpain/actions/runs/11857879246

¡Gracias!

**Comment by dieghernan** [comment]
Gracias, debería estar ya arreglado en la versión en desarrollo
