### ISSUE TITLE
Add national grid data

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/mapSpain#61]
Idea from @mpizarrotig :

- [x]  MTN25, 50:  https://centrodedescargas.cnig.es/CentroDescargas/index.jsp# INFORMACIÓN GEOGRÁFICA DE REFERENCIA
- [x] Grids BDN: https://www.miteco.gob.es/es/biodiversidad/servicios/banco-datos-naturaleza/informacion-disponible/bdn-cart-aux-descargas-ccaa.aspx
- [x] EEA reference grid https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2
- [x] European Reference Grids - ESDAC - European Commission) https://esdac.jrc.ec.europaeu/content/european-reference-grids 
Also potentially https://www.eea.europa.eu/data-and-maps/data/common-european-chorological-grid-reference-system-cgrs

**Comment by dieghernan** [comment]
See https://github.com/rOpenSpain/mapSpain/tree/sianedata/MTN

**Comment by mpizarrotig** [comment]
See https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2 (EEA reference grid)

**Comment by mpizarrotig** [comment]
https://esdac.jrc.ec.europa.eu/content/european-reference-grids (European Reference Grids - ESDAC - European Commission)

**Comment by mpizarrotig** [comment]
See https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/spain-shapefile/at_download/file

**Comment by mpizarrotig** [comment]
See https://www.eea.europa.eu/data-and-maps/data/common-european-chorological-grid-reference-system-cgrs (Common European Chorological Grid Reference System - CGRS)
