### ISSUE TITLE
Does Leaflet-providersESP work with mapview?

### ISSUE THREAD

**Issue by fgoerlich** [rOpenSpain/mapSpain#82]
I find that [Leaflet-providersESP](https://dieghernan.github.io/leaflet-providersESP/preview/) does **not** work with [`mapview`](https://r-spatial.github.io/mapview/index.html) and the `map.types` option. Is that correct?

If I run the [Earthquakes in Tenerife](https://ropenspain.github.io/mapSpain/articles/working_imagery.html#earthquakes-in-tenerife-last-year) example I get the expected result, which are shown on the _web_.

But using `mapview` does not work. Even if is does work with standard [Leaflet-providers](https://leaflet-extras.github.io/leaflet-providers/preview/)

``` r
library(mapview)
mapview(Tenerife.leaf)
```

![](https://i.imgur.com/sUe4hMY.png)

``` r
mapview(Tenerife.leaf, map.type = "OpenTopoMap")
```

![](https://i.imgur.com/LDv1Y6j.png)

``` r
mapview(Tenerife.leaf, map.type = "IDErioja")
```

![](https://i.imgur.com/WiAl1pc.png)

<sup>Created on 2022-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dieghernan** [comment]
I am not sure that mapview alllows to add providers other than the already included in https://leaflet-extras.github.io/leaflet-providers/preview/.

However, you can try this hack as provided in https://mhweber.github.io/2018/11/09/adding-wms-basemap-in-r-with-mapview/:

```r

library(mapSpain)

Tenerife.leaf <-
  esp_get_nuts(
    region = "Tenerife",
    epsg = 4326,
    moveCAN = FALSE
  )

library(mapview)
library(leaflet)

m <- mapview(Tenerife.leaf) 


# Hack: https://mhweber.github.io/2018/11/09/adding-wms-basemap-in-r-with-mapview/
m@map <- m@map %>%
  addProviderEspTiles("Geofisica.Terremotos365dias",
                      group = "Earthquakes"
  )


m
```

![image](https://user-images.githubusercontent.com/25656809/201075626-55672d37-8f2c-4529-b101-841571e35c1c.png)

**Comment by dieghernan** [comment]
See also https://github.com/r-spatial/mapview/issues/347 where the same hack is presented
